# Deployed the cart service pointing to an AWS-managed DynamoDB table in us-east-1.
# Created the DynamoDB table "cart" using AWS CLI prior to deployment

serviceAccount:
  create: false     # Reuse existing service account 
  name: "cart"

app:
  persistence:
    provider: dynamodb
    dynamodb:
      tableName: cart
