# Deployed the catalog service with in-cluster MySQL backed by a PVC on an EKS cluster.

app:
  persistence:
    provider: mysql
    secret:
      password: "catalog123"

mysql:
  create: true
  persistentVolume:
    enabled: true
    size: 1Gi
    storageClass: "gp3"
