# Deployed the catalog service pointing to an externally managed MySQL instance.
# Set mysql.create to false and provided a custom endpoint — no in-cluster DB pod created.

app:
  persistence:
    provider: mysql
    endpoint: "retail-store-sample-db.cri2is6gmf7z.us-east-1.rds.amazonaws.com:3306"
    secret:
      password: "catalog123"

mysql:
  create: false
